---
title: "intermedio 1"
output:
  pdf_document: default
  github_document: default
  html_document: default
  ioslides_presentation: default
  md_document: default
  word_document: default
  slidy_presentation: default
  beamer_presentation: default
date: "18 de febrero de 2018"
subtitle: formato *long & wide*
---
\pagenumbering{gobble}
\pagenumbering{arabic} 
\setlength{\parskip}{2pt}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Tarea Previa a Sesión 2 _-sobre proyecto individual-_
&nbsp;

_el resumen_
&nbsp;

- A partir de tu idea de proyecto individual, elabora una nueva versión del resumen de proyecto individual. 
- Sigue los lineamientos del archivo “iidea-FORMATO.doc”. 
- Guarda el archivo como “iidea2-APODO”, .doc o .docx.

&nbsp;

_la base_
&nbsp;

- A partir de tu idea de proyecto individual, arma la estructura de la base de datos obtenida o a obtener en una planilla de cálculo. Considera si es de formato largo o ancho. 
- En una hoja guarda la base. En otra hoja registra, clasifica y describe las variables involucradas; para ello usa 3 columnas, variable, tipo y descripción. 
- Guarda el archivo como “iidea-APODO-prebase”, .xls o .xlsx.
&nbsp;


##### Envío de archivos

A cursoclinicadedatos@gmail.com
&nbsp;

##### Entrega 

26 de febrero



